In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import MinMaxScaler

from pickle import dump

In [2]:
raw_train_ASOS = pd.read_csv('make_data/train_ASOS_include_past.csv', index_col = 0, encoding = 'CP949')
raw_test1_ASOS = pd.read_csv('make_data/test1_ASOS_include_past.csv', index_col = 0, encoding = 'CP949')
raw_test2_ASOS = pd.read_csv('make_data/test2_ASOS_include_past.csv', index_col = 0, encoding = 'CP949')
raw_test3_ASOS = pd.read_csv('make_data/test3_ASOS_include_past.csv', index_col = 0, encoding = 'CP949')

display(raw_train_ASOS)

,기온,풍속,습도,증기압,이슬점,현지기압,전운량,중하층,지면온도,log_percip,1시간전,2시간전,3시간전,4시간전,5시간전,6시간전
0,17.4,2.4,70.0,13.900000,11.9,1004.1,7.0,4.0,17.250000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,17.6,0.6,67.0,12.633333,10.3,1003.8,7.0,4.0,16.666667,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,17.8,0.5,55.0,11.366667,8.7,1003.5,7.0,4.0,16.083333,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,17.1,1.7,52.0,10.100000,7.1,1003.2,7.0,4.0,15.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,17.1,1.2,47.0,9.466667,6.1,1003.3,8.0,4.0,15.800000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83899,17.3,2.4,78.0,15.400000,13.4,1009.3,7.0,7.0,15.600000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83900,17.3,2.3,78.0,15.400000,13.4,1009.4,6.0,6.0,15.700000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83901,17.0,2.8,80.0,15.500000,13.5,1009.3,7.0,7.0,15.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83902,16.8,1.7,81.0,15.500000,13.5,1009.8,8.0,8.0,14.900000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83903,16.6,1.3,84.0,15.800000,13.8,1010.0,8.0,8.0,14.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
raw_train_AWS = pd.read_csv('make_data/train_AWS_include_past.csv', index_col = 0, encoding = 'CP949')
raw_test1_AWS = pd.read_csv('make_data/test1_AWS_include_past.csv', index_col = 0, encoding = 'CP949')
raw_test2_AWS = pd.read_csv('make_data/test2_AWS_include_past.csv', index_col = 0, encoding = 'CP949')
raw_test3_AWS = pd.read_csv('make_data/test3_AWS_include_past.csv', index_col = 0, encoding = 'CP949')

display(raw_train_AWS)

,마포 강수량,마포 1시간전,마포 2시간전,마포 3시간전,마포 4시간전,마포 5시간전,마포 6시간전,성북 강수량,성북 1시간전,성북 2시간전,...,성동 4시간전,성동 5시간전,성동 6시간전,용산 강수량,용산 1시간전,용산 2시간전,용산 3시간전,용산 4시간전,용산 5시간전,용산 6시간전
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83899,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83900,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83901,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83902,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83903,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
raw_train_add_AWS = pd.concat([raw_train_ASOS, raw_train_AWS], axis = 1)
raw_test1_add_AWS = pd.concat([raw_test1_ASOS, raw_test1_AWS], axis = 1)
raw_test2_add_AWS = pd.concat([raw_test2_ASOS, raw_test2_AWS], axis = 1)
raw_test3_add_AWS = pd.concat([raw_test3_ASOS, raw_test3_AWS], axis = 1)

display(raw_train_add_AWS)

,기온,풍속,습도,증기압,이슬점,현지기압,전운량,중하층,지면온도,log_percip,...,성동 4시간전,성동 5시간전,성동 6시간전,용산 강수량,용산 1시간전,용산 2시간전,용산 3시간전,용산 4시간전,용산 5시간전,용산 6시간전
0,17.4,2.4,70.0,13.900000,11.9,1004.1,7.0,4.0,17.250000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,17.6,0.6,67.0,12.633333,10.3,1003.8,7.0,4.0,16.666667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,17.8,0.5,55.0,11.366667,8.7,1003.5,7.0,4.0,16.083333,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,17.1,1.7,52.0,10.100000,7.1,1003.2,7.0,4.0,15.500000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,17.1,1.2,47.0,9.466667,6.1,1003.3,8.0,4.0,15.800000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83899,17.3,2.4,78.0,15.400000,13.4,1009.3,7.0,7.0,15.600000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83900,17.3,2.3,78.0,15.400000,13.4,1009.4,6.0,6.0,15.700000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83901,17.0,2.8,80.0,15.500000,13.5,1009.3,7.0,7.0,15.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83902,16.8,1.7,81.0,15.500000,13.5,1009.8,8.0,8.0,14.900000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83903,16.6,1.3,84.0,15.800000,13.8,1010.0,8.0,8.0,14.500000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
# target data 추출

train_target_ASOS = raw_train_ASOS['log_percip']
test1_target_ASOS = raw_test1_ASOS['log_percip']
test2_target_ASOS = raw_test2_ASOS['log_percip']
test3_target_ASOS = raw_test3_ASOS['log_percip']

# 어차피 동일
# train_target_add_AWS = raw_train_add_AWS['log_percip']
# test1_target_add_AWS = raw_test1_add_AWS['log_percip']
# test2_target_add_AWS = raw_test2_add_AWS['log_percip']
# test3_target_add_AWS = raw_test3_add_AWS['log_percip']

In [6]:
MM_sc1 = MinMaxScaler()
MM_sc2 = MinMaxScaler()

scaled_train_ASOS = MM_sc1.fit_transform(raw_train_ASOS)
scaled_test1_ASOS = MM_sc1.transform(raw_test1_ASOS)
scaled_test2_ASOS = MM_sc1.transform(raw_test2_ASOS)
scaled_test3_ASOS = MM_sc1.transform(raw_test3_ASOS)

scaled_train_add_AWS = MM_sc2.fit_transform(raw_train_add_AWS)
scaled_test1_add_AWS = MM_sc2.fit_transform(raw_test1_add_AWS)
scaled_test2_add_AWS = MM_sc2.fit_transform(raw_test2_add_AWS)
scaled_test3_add_AWS = MM_sc2.fit_transform(raw_test3_add_AWS)

In [7]:
np.save('make_data/scaled_train_ASOS', scaled_train_ASOS)
np.save('make_data/scaled_test1_ASOS', scaled_test1_ASOS)
np.save('make_data/scaled_test2_ASOS', scaled_test2_ASOS)
np.save('make_data/scaled_test3_ASOS', scaled_test3_ASOS)

np.save('make_data/scaled_train_add_AWS', scaled_train_add_AWS)
np.save('make_data/scaled_test1_add_AWS', scaled_test1_add_AWS)
np.save('make_data/scaled_test2_add_AWS', scaled_test2_add_AWS)
np.save('make_data/scaled_test3_add_AWS', scaled_test3_add_AWS)

dump(MM_sc1, open('make_data/MM_sc_ASOS.pkl', 'wb'))
dump(MM_sc2, open('make_data/MM_sc_add_AWS.pkl', 'wb'))

In [8]:
np.save('make_data/train_target', train_target_ASOS)
np.save('make_data/test1_target', test1_target_ASOS)
np.save('make_data/test2_target', test2_target_ASOS)
np.save('make_data/test3_target', test3_target_ASOS)